### ISSUE TITLE
If you do not move when you start the blocks are not erased

### ISSUE THREAD

**Issue by UnEnanoMas** [OguzhanUmutlu/TNTRun#5]
![image](https://user-images.githubusercontent.com/63286108/117291097-db12a580-ae6e-11eb-8137-8ef2d0ea5d78.png)

If you move the camera a little if they start to remove the blocks, and even if you stay still then they will be removed, but if you stay still at first, no.

Dev17

**Comment by OguzhanUmutlu** [comment]
fixed
