### ISSUE TITLE
Delete 2 blocks high, no 1

### ISSUE THREAD

**Issue by UnEnanoMas** [OguzhanUmutlu/TNTRun#6]
![image](https://user-images.githubusercontent.com/63286108/117291316-1d3be700-ae6f-11eb-832b-9b2503cfca1e.png)

Currently TNTRun consists of 2 objects, the TNT and blocks such as sand or gravel.

When you are running, only 1 of them is deleted, and then when you fall to the tnt, it is deleted, but it is quite bad, I wanted to know if 2 blocks of height can be removed at the same time

**Comment by OguzhanUmutlu** [comment]
you can change it in line 241
https://github.com/OguzhanUmutlu/TNTRun/blob/main/src/OguzhanUmutlu/TNTRun/arena/Arena.php#L241
